require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DefaultsController do

  # This should return the minimal set of attributes required to create a valid
  # Default. As you add validations to Default, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefaultsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all defaults as @defaults" do
      default = Default.create! valid_attributes
      get :index, {}, valid_session
      assigns(:defaults).should eq([default])
    end
  end

  describe "GET show" do
    it "assigns the requested default as @default" do
      default = Default.create! valid_attributes
      get :show, {:id => default.to_param}, valid_session
      assigns(:default).should eq(default)
    end
  end

  describe "GET new" do
    it "assigns a new default as @default" do
      get :new, {}, valid_session
      assigns(:default).should be_a_new(Default)
    end
  end

  describe "GET edit" do
    it "assigns the requested default as @default" do
      default = Default.create! valid_attributes
      get :edit, {:id => default.to_param}, valid_session
      assigns(:default).should eq(default)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Default" do
        expect {
          post :create, {:default => valid_attributes}, valid_session
        }.to change(Default, :count).by(1)
      end

      it "assigns a newly created default as @default" do
        post :create, {:default => valid_attributes}, valid_session
        assigns(:default).should be_a(Default)
        assigns(:default).should be_persisted
      end

      it "redirects to the created default" do
        post :create, {:default => valid_attributes}, valid_session
        response.should redirect_to(Default.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved default as @default" do
        # Trigger the behavior that occurs when invalid params are submitted
        Default.any_instance.stub(:save).and_return(false)
        post :create, {:default => { "user" => "invalid value" }}, valid_session
        assigns(:default).should be_a_new(Default)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Default.any_instance.stub(:save).and_return(false)
        post :create, {:default => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested default" do
        default = Default.create! valid_attributes
        # Assuming there are no other defaults in the database, this
        # specifies that the Default created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Default.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => default.to_param, :default => { "user" => "" }}, valid_session
      end

      it "assigns the requested default as @default" do
        default = Default.create! valid_attributes
        put :update, {:id => default.to_param, :default => valid_attributes}, valid_session
        assigns(:default).should eq(default)
      end

      it "redirects to the default" do
        default = Default.create! valid_attributes
        put :update, {:id => default.to_param, :default => valid_attributes}, valid_session
        response.should redirect_to(default)
      end
    end

    describe "with invalid params" do
      it "assigns the default as @default" do
        default = Default.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Default.any_instance.stub(:save).and_return(false)
        put :update, {:id => default.to_param, :default => { "user" => "invalid value" }}, valid_session
        assigns(:default).should eq(default)
      end

      it "re-renders the 'edit' template" do
        default = Default.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Default.any_instance.stub(:save).and_return(false)
        put :update, {:id => default.to_param, :default => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested default" do
      default = Default.create! valid_attributes
      expect {
        delete :destroy, {:id => default.to_param}, valid_session
      }.to change(Default, :count).by(-1)
    end

    it "redirects to the defaults list" do
      default = Default.create! valid_attributes
      delete :destroy, {:id => default.to_param}, valid_session
      response.should redirect_to(defaults_url)
    end
  end

end
